export enum Vault {
  PERSONAL = 'PERSONAL',
  BUSINESS = 'BUSINESS',
}

export enum HttpErrorStatus {
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  INTERNAL_SERVER_ERROR = 500,
}
